### ISSUE TITLE
Stuck at "Waiting for clash main menu"

### ISSUE THREAD

**Issue by peachlooter** [matthewmiglio/py-clash-bot#167]
Since the February season update, the bot stucks at "Waiting for clash main menu".

**Comment by zeitgenossek2** [comment]
holy shit 1 month ago and no one responded ?

**Comment by matthewmiglio** [comment]
This issue has been solved. 

However, admittedly, the bot is very buggy since the February update and I still need to handle some of the new clash GUI changes.

The bot can still handle its basic operations (like card upgrading and fight starting). 

TLDR; this issue is fixed, but the bot will still be very buggy for now

**Comment by marmig0404** [comment]
This issue should be fixed in [v1.1.2](https://github.com/matthewmiglio/py-clash-bot/releases/tag/v1.1.2)

**Comment by raivenz23** [comment]
just a newbie here. 
having this error in v2.0.0
wait_for_clash_main_menu() took too long waiting for clash main.
how to fix this  sir martinmiglio Thanks in advance
