### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Mikel182** [matthewmiglio/py-clash-bot#39]
Hello, I have followed all the steps you mention in the guide, still not working

Could you please do a video-tutorial about how to install & make it working?

After following steps appears a CMD window that automatically closes

Thank you

**Comment by Mikel182** [comment]
I am using latest versión of MEMU - 8.0.2 (28.06.2022)

**Comment by marmig0404** [comment]
The **[v0.4.27 release](https://github.com/matthewmiglio/py-clash-bot/releases/tag/v0.4.27)** should have a fix for keeping errors on screen for bug reporting purposes.

**Comment by Mikel182** [comment]
Hello

I update you - screenshot attached.

[https://imgur.com/a/WBwlCOJ](url)

It still appears this, idk what is missing

Regards

Thank you.

**Comment by matthewmiglio** [comment]
Hi Mikel182,

If the program is not detecting that one or either of the programs is open there must be an issue with the naming of the Multi-Instance Manager or MEmu on your PC.

This issue may be caused by installing/running MEmu in a language other than English.

Could you attach a screenshot of the window names of your MEmu client and your Multi-Instance Manager?

**Comment by matthewmiglio** [comment]
I appreciate you providing those screenshots.

It seems the problem is that your Multi-Instance Manager has a window name that the bot isn't used to. This may be caused by using an out-of-date version of MEmu.

A new release (v0.4.29) is available and accounts for this issue.

Please try this new version and let us know how it goes.
